// Generated by Dagger (https://dagger.dev).
package com.app2u.app2udemo.commons.domain.executor;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class JobThread_Factory implements Factory<JobThread> {
  @Override
  public JobThread get() {
    return newInstance();
  }

  public static JobThread_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static JobThread newInstance() {
    return new JobThread();
  }

  private static final class InstanceHolder {
    private static final JobThread_Factory INSTANCE = new JobThread_Factory();
  }
}
