// Generated by Dagger (https://dagger.dev).
package com.app2u.app2udemo.commons.domain.executor;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class UIThread_Factory implements Factory<UIThread> {
  @Override
  public UIThread get() {
    return newInstance();
  }

  public static UIThread_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static UIThread newInstance() {
    return new UIThread();
  }

  private static final class InstanceHolder {
    private static final UIThread_Factory INSTANCE = new UIThread_Factory();
  }
}
